server:
  port: 8084

spring:
  application:
    name: data-collection-service
  cloud:
    compatibility-verifier:
      enabled: false
    nacos:
      discovery:
        server-addr: 192.168.118.130:8848
        namespace: dev
        group: ENERGY_PLATFORM
      config:
        server-addr: 192.168.118.130:8848
        namespace: dev
        group: ENERGY_PLATFORM
        import-check:
          enabled: false
  datasource:
    url: jdbc:mysql://192.168.118.130:3306/energy_monitor?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver